/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    GenericTable: typeof import('./components/common/GenericTable.vue')['default']
    GenericView: typeof import('./components/common/GenericView.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MenuItem: typeof import('./components/menu/MenuItem.vue')['default']
    MenuParent: typeof import('./components/menu/MenuParent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
